import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
    flex: 1,
    backgroundColor: "#25292e",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    textAlign: "center",
    color: "#ffffff",
    justifyContent: "space-between",
    paddingTop: 20,
    paddingBottom: 40,
    paddingHorizontal: 8,
  },
  text: {
    color: "#ffffff",
  },
  grid :{
    flex: 1,
    flexDirection: "column",
  },
  daysHeader :{
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderColor: "#3a3f45",
  },
  headerCell :{
    flex: 1,
    alignItems: "center",
    textAlign: "center",
    color: "#ffffff",
    height: 25,
  },
  cell :{
    flex: 1,
    alignItems: "center",
    textAlign: "center",
    justifyContent: "center",
    borderWidth: 0.5,
    borderColor: "#3a3f45",
    color: "#ffffff",
  },
  modalBox: {
    width: "80%",
    height: "80%",
    backgroundColor: "#25292e",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#3a3f45",
    overflow: "hidden",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.65)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#3a3f45",
  },
  modalSmallHeader: {
    padding: 12,
    borderBottomWidth: 0.5,
    borderBottomColor: "#3a3f45",
  },
  entryButton: {
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#3a3f45",
    width: "80%",
    alignSelf: "center",
    marginVertical: 8,
  },
  toggleButton: {
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#3a3f45",
    flex: 1,
    alignItems: "center",
    marginHorizontal: 4,
  },
  fieldLabel: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  inputTextBox: {
    borderWidth: 1,
    borderColor: "#3a3f45",
    borderRadius: 8,
    padding: 8,
    marginBottom: 16,
    fontSize: 14,
    color: "#ffffff",
    paddingHorizontal: 12,
    paddingVertical: 10,
  }
});